module.exports = {
    davinci_trigger: '/bot',
    davinci_variation: 1,
    davinci_words: 4000,
    davinci_header_text: 'Chat GPT',
    dalle_trigger: '/img',
    image_size: '1024x1024',
    dalle_text: "This image was generated by A.I. (DALL-E)",
    jshelper_trigger: '/js',
    jshelper_variation: 1,
    jshelper_words: 1000,
}